services:
  - type: web
    name: monblog-pulse
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: "Pulse"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: monblog-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: monblog-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: monblog-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: monblog-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: monblog-db
          property: password
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error

databases:
  - name: monblog-db
    plan: free
    region: frankfurt